services:
  postgres:
    image: postgis/postgis:17-3.5-alpine
    ports:
      - 5433:5432
    volumes:
      - travel_pgdb:/var/lib/postgresql/data
      - ./init-db.sh/01_create_databases.sh:/docker-entrypoint-initdb.d/01_create_databases.sh
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-travel}
      - POSTGRES_USER=${POSTGRES_USER:-travel}
      - POSTGRES_MULTIPLE_DATABASES=travel,travel_staging,travel_prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-travel}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - travel_net

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - DOCKER_ENV=true
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    networks:
      - travel_net
    volumes:
      - .:/app
    entrypoint: ["/app/entrypoint.sh"]
    command: []
    env_file:
      - ${ENV_FILE:-.env.dev}

  valkey:
    image: valkey/valkey:7.2-alpine
    ports:
      - 6378:6379
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - travel_net

volumes:
  travel_pgdb:
  valkey_data:

networks:
  travel_net:
